package com.automation.core.enums;

public enum VCATCheckpoint {

	PAYMNTASSMPTNCHNGDNWTOW, TECHDISAGRDSYSRECMNDREPAIR,ARCDEALER,ENGINEERINGREVIEW,
	MANUFACTURINGDATE, MILEAGE, MONTHSINSERVICE,VIN,DEALERSPECIFIC,ADDITIONALRULES,
	INSERVICEDATEUNAVAILABLE,SERVICECONTRACTCOVERAGE,PARTSWARRANTYCOVERAGE,ROUTETOVCAT,ROUTETONESNA;

	
}
